### ISSUE TITLE
LXD support and evolution?

### ISSUE THREAD

**Issue by juju4** [chifflier/ansible-lxc-ssh#2]
LXD support seems easy: just replace s/lxc-attach --name /lxc exec /

but there are some issues arising for some module like user or file transfer (lxc file push/pull).

Any plan for evolution?

Thanks

**Comment by spinitron** [comment]
@juju4 ansible now [includes](https://github.com/ansible/ansible/tree/7542dae26baa0d74dbb097a1f7c4b730375e8b4d/lib/ansible/plugins/connection) an lxd connection plugin. 

the included lxc plugin in that dir is limited to lxc running locally on the control machine.
