### ISSUE TITLE
Any plans to make this compatible with latest Ansible 2.4.x?

### ISSUE THREAD

**Issue by nodje** [chifflier/ansible-lxc-ssh#6]
`from ansible.compat.six` can't be found in latest Ansible, resulting in an error when using the plugin.

Looks like your connection plugin is the only one that enables ssh-less management of remote lxc containers. The Openstack one is unusable for some reason and there's zero documentation and the official lxc plugin doesn't support remote lxc containers.

Cheers

**Comment by lgeorget** [comment]
Can you give a try to https://github.com/lgeorget/ansible-lxc-ssh? I rebased the plugin onto the Ansible 2.4 ssh connection plugin.

**Comment by nodje** [comment]
Well done man, it works, thanks!
